[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/_stcore/health"
interval = 30
timeout = 300
retries = 5
startPeriod = 120

[deploy.env]
PORT = "8501" 