[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build -t app ."

[deploy]
startCommand = "docker run --init -p $PORT:8501 app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 30
healthcheckInterval = 15

[deploy.env]
PORT = "8501"
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
TZ = "UTC"

[deploy.resources]
cpu = 1024
memory = 2048 