[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckTimeout = 180

[deploy.healthcheck]
path = "/_stcore/health"
interval = 45
timeout = 180
retries = 3
startPeriod = 180

[deploy.env]
PORT = "8501"
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLE_CORS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false" 