[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 50
enableXsrfProtection = false
enableCORS = true
headless = true
runOnSave = false
maxMessageSize = 200
enableWebsocketCompression = false
enableStaticServing = true

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#2196F3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "debug"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"
caching = true 